import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/models/media_item.dart';

/// Placeholder subtitle service. Snaptube lets users pick subtitle language
/// inside the download sheet ("More Formats → Subtitles/CC"). For the MVP we
/// just expose a stub; full YouTube subtitle extraction requires the
/// `youtube_explode_dart` v3+ API which exposes closed-captions.
class SubtitleService {
  /// Returns the list of available caption tracks for [videoId].
  ///
  /// Currently always returns an empty list — the underlying youtube_explode
  /// version we use does not yet expose closed captions in the manifest.
  /// When we upgrade to v3.x, this method should call into
  /// `_yt.videos.closedCaptions.getManifest(videoId)`.
  Future<List<SubtitleTrack>> listTracks(String videoId) async => [];

  /// Convenience overload: list tracks for a [MediaItem] (YouTube only).
  Future<List<SubtitleTrack>> listTracksFor(MediaItem item) async => [];

  /// Download a single subtitle track as plain text.
  Future<String> downloadTrack(SubtitleTrack track) async => '';
}

/// Represents one subtitle track.
class SubtitleTrack {
  const SubtitleTrack({
    required this.language,
    required this.name,
    required this.isAutoGenerated,
    required this.url,
  });

  final String language;
  final String name;
  final bool isAutoGenerated;
  final String url;

  @override
  String toString() => '$name ($language)${isAutoGenerated ? ' · auto' : ''}';
}

/// Riverpod provider.
final subtitleServiceProvider = Provider<SubtitleService>((ref) {
  return SubtitleService();
});
